CREATE TABLE IF NOT EXISTS oshi (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'other',
  color TEXT NOT NULL DEFAULT '#ec4899',
  image_url TEXT,
  memo TEXT,
  created_at_ms BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS goods (
  id TEXT PRIMARY KEY,
  oshi_id TEXT NOT NULL REFERENCES oshi(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL DEFAULT 0,
  date TEXT NOT NULL,
  image_url TEXT,
  memo TEXT
);

CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  oshi_id TEXT NOT NULL REFERENCES oshi(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'other',
  date TEXT NOT NULL,
  price NUMERIC NOT NULL DEFAULT 0,
  attended BOOLEAN NOT NULL DEFAULT false,
  memo TEXT
);

ALTER TABLE oshi ENABLE ROW LEVEL SECURITY;
ALTER TABLE goods ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public_all" ON oshi FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "public_all" ON goods FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "public_all" ON events FOR ALL USING (true) WITH CHECK (true);
